
# https://docs.microsoft.com/en-us/dotnet/architecture/microservices/multi-container-microservice-net-applications/multi-container-applications-docker-compose

version: "3.8"

services:
  oauth:
    image: node:latest
    command: sh -c "yarn install && yarn run oauth_dev"
    working_dir: /app
    ports:
      - 3002:3000
    volumes:
      - ./:/app
      - server-node_modules:/app/node_modules

volumes:
  server-node_modules:
  

  
# docker-compose up -d
# docker-compose logs -f
# docker-compose down

# docker-compose -f .\docker-compose.dev.yml up -d
# docker-compose -f .\docker-compose.dev.yml logs -f
# docker-compose -f .\docker-compose.dev.yml down


# docker exec -it referendum-server_server_1 nginx -s reload
# docker-compose -f .\docker-compose.dev.yml restart react-client