
# docker-compose up -d
# docker-compose logs -f
# docker-compose down

# docker-compose -f .\docker-compose.dev.yml up
# docker-compose -f .\docker-compose.dev.yml logs -f
# docker-compose -f .\docker-compose.dev.yml down

version: "3.8"

services:
  mysql:
    image: mysql:latest
    volumes:
      - referendum-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: referendum
  
  app:
    image: node:latest
    # omitted yarn install, running on windows machine
    # and npm cannot make link in ntfs
    command: sh -c "yarn run dev"
    ports:
      - 3001:3000
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DB: referendum
    depends_on:
      - mysql

  react-client:
    image: node:latest
    working_dir: /app
    ports:
      - 3000:3000
    volumes:
      - react-client-data:/app
      - ../referendum-client/public:/app/public
      - ../referendum-client/src:/app/src
      - ../referendum-client/.env:/app/.env
      - ../referendum-client/package.json:/app/package.json
    command: sh -c "yarn install && yarn run start"
    
  
  server:
    # docker exec -it referendum-server_server_1 nginx -s reload
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8000:80
      - 8080:8001
    depends_on:
      - app
      - react-client



volumes:
  referendum-mysql-data:
  react-client-data: